### PR TITLE
Test multiple version mongo

### PR DESCRIPTION
**Pull request by chicco785**
Officially tested mongo versions:

* 3.4
* 3.2
* 3.0

Officially tested docker versions:

* 17.06
* 17.09

### CODE REVIEW

**Comment by chicco785** [comment]
cf #18

**Review by taliaga — APPROVED** [review]
In matrix, defining the list of MONGO_VERSION and DOCKER_VERSION should be enough (i.e, no need to declaratively combine them all)

**Comment by chicco785** [comment]
@taliaga i am not exactly sure how to do that, do you have an example?

**Comment by chicco785** [comment]
maybe i got it, are you referring to the installation process?
unfortunately is not that simple due to the different key for each mongo version and to the number of versioning in docker which is different from the one in ubuntu packaging (which is used to set up a client for the testing)

**Pull request merged**
